import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from './components/navBar';
import { NextFont } from 'next/dist/compiled/@next/font';
import { ToasterContext } from './context/ToastContext';
import { ReactNode, Suspense } from 'react';

const inter: NextFont = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <Suspense>
                <body className={inter.className}>
                    <ToasterContext />
                    <Navbar />
                    <div>{children}</div>
                </body>
            </Suspense>
        </html>
    );
}
